[package]
name = "rss-autogen-giscus"
version = "0.1.0"
authors = ["Cameron Rodriguez <dev@camrod.me>"]
edition = "2021"
license = "Apache-2.0"
description = "A small program to autogenerate GitHub Discussions from Atom/RSS feeds."

[dependencies]
feed-rs = "~1.3"
octocrab = "~0.23"
reqwest = "~0.11"
serde_json = "~1.0"
scraper = "~0.16"
tokio = { version = "~1.28", features = ["macros", "rt-multi-thread"] }
url = "~2.3"
